vim.cmd("set nu")

vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set smarttab")
vim.cmd("set expandtab")
vim.cmd("set smartindent")
vim.cmd("set autoindent")

vim.cmd("set signcolumn=yes")
vim.cmd("set clipboard=unnamedplus")
vim.cmd("set spelllang=en_us,pt_br")
vim.cmd("set spell")
vim.cmd("set relativenumber")
vim.cmd("set cursorline")
vim.cmd("set list")
vim.cmd("set lcs+=space:·")

vim.cmd("set mouse=")
