unbind r 
bind r source-file ~/.tmux.conf \; display "Reloaded tmux config"
# Fix Colors
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g prefix C-a
set -g default-terminal "tmux-256color"

# Enable mouse support 
set -g mouse on

bind-key h select-pane -L 
bind-key j select-pane -D 
bind-key k select-pane -U 
bind-key l select-pane -R

# Popups 
bind-key t popup -E -h 90% -w 90% -x C -y C -d '#{pane_current_path}'
bind-key T popup -E -h 90% -w 90% -x C -y C
bind-key h popup -E -h 90% -w 90% -x C -y C "htop"
bind-key v popup -E -h 90% -w 90% -x C -y C "nvim"
bind-key g popup -E -h 90% -w 90% -x C -y C -d '#{pane_current_path}' "lazygit"
bind-key G popup -E -h 90% -w 90% -x C -y C "lazygit"


bind s choose-tree -sZ -O name

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.1.2'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "none"
# set -g @catppuccin_window_status_style "none"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

set -g @catppuccin_window_left_separator "█" 
set -g @catppuccin_window_right_separator "█" 
set -g @catppuccin_window_middle_separator "█"
set -g @catppuccin_status_left_separator "█" 
set -g @catppuccin_status_right_separator "█"

# Optional: Ensure separators connect seamlessly with the status bar fill
set -g @catppuccin_status_connect_separator "yes"

set -g status-position top
set -g status-justify "absolute-centre"

set -g status-left-length 100
set -g status-left ""
set -ag status-left "#{E:@catppuccin_status_session}"
set -ag status-left "#{E:@catppuccin_status_application}"
set -ag status-left "#{E:@catppuccin_status_window}"

set -g status-right-length 100
set -g status-right ""
set -ag status-right "#{E:@catppuccin_status_date_time}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -ag status-right "#{E:@catppuccin_status_host}"

# configure tmux-resurrect 
set -g @resurrect-processes 'ssh nvim htop lazygit'
set -g @resurrect-strategy-nvim 'session'
# set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-save-command-strategy 'pgrep'

set -g @continuum-restore 'on'
set -g @continuum-boot 'on'
run '~/.tmux/plugins/tpm/tpm'
