- name: apt
  become: true
  when: ansible_facts['os_family'] == 'Debian'
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: yum 
  become: true
  when: ansible_facts['os_family'] == 'RedHat'
  yum:
    name: '*'
    state: latest
