- name: setup-ubuntu
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ../vars.yml
  roles:
      - role: create-dotfiles-links
    
      - role: install-defaults

      - role: install-lazygit

      - role: add-known-host

      - role: install-zsh

      - role: install-asdf

      - role: install-nvim

      - role: install-tmux

      - role: install-docker

  post_tasks:
    - name: default-shell
      become: true
      user:
        name: "{{ user_name }}"
        shell: /usr/bin/zsh
        update_password: on_create