- name: folder
  become: true
  file:
      path: "{{ volume_path }}"
      state: directory

- name: mount volume
  become: true
  mount:
      path: "{{ volume_path }}"
      src: "{{ volume_device }}"
      fstype: "{{ volume_type }}"
      state: mounted
      boot: "{{ boot | default(true) }}"

- name: permissions
  become: true
  file:
      path: "{{ volume_device }}"
      owner: "{{ volume_owner }}"
      group: "{{ volume_owner }}"
      mode: 0755

