- name: install python3
  apt:
    name: 
      - python3
      - python3-apt
      - python3-minimal
      - python3-passlib
      - python3-pip
    state: present

- name: symbolic link python3 to python
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link 

- name: set ansible python interpreter
  set_fact:
    ansible_python_interpreter: /usr/bin/python3
